wandb_version: 1

factor:
  value: 0.3761607825746237
learning_rate:
  value: 1.2764065824334371e-05
max_length:
  value: 128
num_train_epochs:
  value: 2
patience:
  value: 2
per_device_batch_size:
  value: 8
scheduler_type:
  value: reduce_on_plateau
warmup_ratio:
  value: 0.14326712943618436
weight_decay:
  value: 0.06006792378729758
